version: "2"
prepare:
  fetch:
    - "https://raw.githubusercontent.com/internetee/style-guide/master/ruby/.rubocop.yml"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
    channel: rubocop-0-62
exclude_patterns:
  - "bin/"
  - "test/"